name: jm

services:
  claude:
    image: ${IMAGE:-claude}:${TAG:-latest}
    build:
      context: ./
      dockerfile: Containerfile
      args:
        BUILD_INFO_CTIME: ${BUILD_INFO_CTIME:-latest}
        BUILD_INFO_GIT_COMMIT: ${BUILD_INFO_GIT_COMMIT:-latest}
    userns_mode: "keep-id:uid=1000,gid=1000"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    environment:
      - CONTAINER_HOST=${CLAUDE_REMOTE_PODMAN:-}
      # CLAUDE_REMOTE_PODMAN: ssh://user@machine/<podman.sock path>
      - CONTAINER_SSHKEY=/home/user/.ssh/id_ed25519
    volumes:
      - ${CLAUDE_CONTAINER_CONFIG:-~/.config/jm/claude/conf}:/home/user/.config/claude
      - ${CLAUDE_CONTAINER_DATA:-~/.local/share/jm/claude/data}:/home/user/.local/share/claude
      - ${CLAUDE_CONTAINER_APP:-./}:/app
      - ${CLAUDE_CONTAINER_APP_GIT_DIR:-../main/.git:/src/main/.git}:ro
      - ./.git.container:/app/.git:ro
      - ${CLAUDE_KNOWN_HOSTS:-~/.config/jm/claude/known_hosts}:/home/user/.ssh/known_hosts:ro
      - /etc/hosts:/etc/hosts:ro
      - ${CLAUDE_SSH_KEY:-/dev/null}:/home/user/.ssh/id_ed25519:ro
